apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend-deployment
  labels:
    component: myfrontend
    app: my-myfrontend

spec:
  template:
    metadata:
      name: myfrontend-pod
      labels:
        component: myfrontend
        app: my-myfrontend
    spec:
      containers:
        - name: myfrontend-container
          image: mordowska/myfrontend
  replicas: 3
  selector:
    matchLabels:
      component: myfrontend
      app: my-applb2
