version: '3'

services:
    myredis:
        image: 'redis:alpine'
    mypostgres:
        image: 'postgres:alpine'
        environment: 
            - POSTGRES_PASSWORD=1qaz2wsx
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
    mynginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./mynginx
        ports: 
            - '9090:80'
        image: mordowska/mynginx
    mybackend:
        build:
            dockerfile: Dockerfile.dev
            context: ./mybackend
        depends_on: 
            - 'mypostgres'
            - 'myredis'
            - 'mynginx'
        volumes:
            - /opt/app/node_modules
            - /home/ubuntu/devops/projekt/mybackend/:/opt/app
        environment:
            - POSTGRES_PASSWORD=1qaz2wsx
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - REDIS_HOST=myredis
            - POSTGRES_HOST=mypostgres
        ports:
            - "5000:4000" 
        image: mordowska/mybackend
    myfrontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./myfrontend
        depends_on: 
            - 'mynginx'
        volumes:
            - /opt/app/node_modules
            - ./myfrontend:/opt/app
        image: mordowska/myfrontend
