apiVersion: v1
kind: Service
metadata:
  name: mybackendlb-node-port
  labels:
    component: backend
    app: my-applb
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31100
  selector:
    component: backend
    app: my-applb2